version: '3.8'

services:
  backend:
    build: ./backend
    container_name: iaib-backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/notifications_db
      - PORT=5000
      - JWT_SECRET=my_jwt_secret_change_in_production
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: iaib-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: iaib-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notifications_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: 